name: EDSR-LWx4
model_type: SRModel_
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0
data_range: 255
backbone_freeze: false

# dataset and data loader settings
datasets:
  train:
    name: DIV2K
    type: PairedImageDataset
    dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub
    dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic/X4_sub
    meta_info_file: fga/data/meta_info/meta_info_DIV2K800sub_GT.txt
    io_backend:
      type: disk

    gt_size: 192
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 6
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: datasets/Set5/GTmod12/GT
    dataroot_lq: datasets/Set5/GTmod12/LRbicx4
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: datasets/Set14/GTmod12/GT
    dataroot_lq: datasets/Set14/GTmod12/LRbicx4
    io_backend:
      type: disk

# network structures
network_g:
  type: EDSR_
  n_colors: 3
  n_feats: 64
  res_scale: 1
  n_resblocks: 16
  scale: [4]
  rgb_range: 255

path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up


  # loss
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
    frc_auc:
      type: calculate_frc_auc
      num_rho: 64
      full: true
    qtr_frc_auc:
      type: calculate_frc_auc
      num_rho: 64
      full: false


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~